// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2up93M7U36S9YbL6etTJZRNRilrW3o-c',
    appId: '1:253510212165:web:389c1648ff0e59663f612c',
    messagingSenderId: '253510212165',
    projectId: 'safora-d11a4',
    authDomain: 'safora-d11a4.firebaseapp.com',
    storageBucket: 'safora-d11a4.firebasestorage.app',
    measurementId: 'G-8M6461GTRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7XwcjNnRwiyStcdFadlrLmQNbB2aNSsA',
    appId: '1:253510212165:android:adf38540403e2bc33f612c',
    messagingSenderId: '253510212165',
    projectId: 'safora-d11a4',
    storageBucket: 'safora-d11a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCREW_2KKhCxlBkuiooV5dKT3UYabKfqv4',
    appId: '1:253510212165:ios:959bda5e4206d1603f612c',
    messagingSenderId: '253510212165',
    projectId: 'safora-d11a4',
    storageBucket: 'safora-d11a4.firebasestorage.app',
    iosBundleId: 'com.example.safora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCREW_2KKhCxlBkuiooV5dKT3UYabKfqv4',
    appId: '1:253510212165:ios:959bda5e4206d1603f612c',
    messagingSenderId: '253510212165',
    projectId: 'safora-d11a4',
    storageBucket: 'safora-d11a4.firebasestorage.app',
    iosBundleId: 'com.example.safora',
  );
}
